spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    timeout: 2000

  jpa:
    show-sql: true
  cache:
    type: redis
jwt:
  secret: javainuse

